CREATE TABLE registerUser (
   id TEXT PRIMARY KEY UNIQUE NOT NULL,
   username VARCHAR(200) UNIQUE NOT NULL,
   email VARCHAR (200) UNIQUE NOT NULL,
   password VARCHAR(100) NOT NULL,
   cpf VARCHAR(14) UNIQUE NOT NULL

)